default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: events_management_platform_development

test:
  <<: *default
  database: events_management_platform_test

production:
  <<: *default
  database: events_management_platform_production
  username: events_management_platform
  password: <%= ENV["EVENTS_MANAGEMENT_PLATFORM_DATABASE_PASSWORD"] %>
